{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "a7536d00",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "welcome to library\n",
      "😄\n",
      "enter your user_name:mohitgupta\n",
      "enter your password(alphanumeric):mohit@22\n",
      "successfully login.\n",
      "total avalible book: 60\n",
      "\n",
      "        type 1 to add_book\n",
      "        type 2 to stock details\n",
      "        type 3 to borrow_book\n",
      "        type 4 to return_book\n",
      "        type 5 to exit\n",
      "        \n",
      "enter your choice:1\n",
      "enter your book:java\n",
      "how many book you add:2\n",
      "total avalible book: 62\n",
      "\n",
      "        type 1 to add_book\n",
      "        type 2 to stock details\n",
      "        type 3 to borrow_book\n",
      "        type 4 to return_book\n",
      "        type 5 to exit\n",
      "        \n",
      "enter your choice:1\n",
      "enter your book:java\n",
      "how many book you add:5\n",
      "total avalible book: 67\n",
      "\n",
      "        type 1 to add_book\n",
      "        type 2 to stock details\n",
      "        type 3 to borrow_book\n",
      "        type 4 to return_book\n",
      "        type 5 to exit\n",
      "        \n",
      "enter your choice:3\n",
      "avalible book\n",
      "book name \t quantity\n",
      "python \t\t 10\n",
      "java \t\t 27\n",
      "math \t\t 10\n",
      "novel \t\t 20\n",
      "enter your name:kanu\n",
      "which book you want:java\n",
      "how many book you want:4\n",
      "successfully borrowed\n",
      "total avalible book: 63\n",
      "\n",
      "        type 1 to add_book\n",
      "        type 2 to stock details\n",
      "        type 3 to borrow_book\n",
      "        type 4 to return_book\n",
      "        type 5 to exit\n",
      "        \n",
      "enter your choice:3\n",
      "avalible book\n",
      "book name \t quantity\n",
      "python \t\t 10\n",
      "java \t\t 23\n",
      "math \t\t 10\n",
      "novel \t\t 20\n",
      "enter your name:rekha\n",
      "which book you want:math\n",
      "how many book you want:5\n",
      "successfully borrowed\n",
      "total avalible book: 58\n",
      "\n",
      "        type 1 to add_book\n",
      "        type 2 to stock details\n",
      "        type 3 to borrow_book\n",
      "        type 4 to return_book\n",
      "        type 5 to exit\n",
      "        \n",
      "enter your choice:3\n",
      "avalible book\n",
      "book name \t quantity\n",
      "python \t\t 10\n",
      "java \t\t 23\n",
      "math \t\t 5\n",
      "novel \t\t 20\n",
      "enter your name:novel\n",
      "which book you want:python\n",
      "how many book you want:2\n",
      "successfully borrowed\n",
      "total avalible book: 56\n",
      "\n",
      "        type 1 to add_book\n",
      "        type 2 to stock details\n",
      "        type 3 to borrow_book\n",
      "        type 4 to return_book\n",
      "        type 5 to exit\n",
      "        \n",
      "enter your choice:3\n",
      "avalible book\n",
      "book name \t quantity\n",
      "python \t\t 8\n",
      "java \t\t 23\n",
      "math \t\t 5\n",
      "novel \t\t 20\n",
      "enter your name:kailash\n",
      "which book you want:python\n",
      "how many book you want:5\n",
      "successfully borrowed\n",
      "total avalible book: 51\n",
      "\n",
      "        type 1 to add_book\n",
      "        type 2 to stock details\n",
      "        type 3 to borrow_book\n",
      "        type 4 to return_book\n",
      "        type 5 to exit\n",
      "        \n",
      "enter your choice:3\n",
      "avalible book\n",
      "book name \t quantity\n",
      "python \t\t 3\n",
      "java \t\t 23\n",
      "math \t\t 5\n",
      "novel \t\t 20\n",
      "enter your name:rohit\n",
      "which book you want:python\n",
      "how many book you want:4\n",
      "sorry that much quantity you want not available\n",
      "total avalible book: 51\n",
      "\n",
      "        type 1 to add_book\n",
      "        type 2 to stock details\n",
      "        type 3 to borrow_book\n",
      "        type 4 to return_book\n",
      "        type 5 to exit\n",
      "        \n",
      "enter your choice:2\n",
      "stock details\n",
      "\n",
      "            press 1 for available book details\n",
      "            prees 2 for borrow book details\n",
      "            press 3 for return book details\n",
      "            \n",
      "enter above option:2\n",
      "borrow book detalis\n",
      "{'kanu': {'java': 4}, 'rekha': {'math': 5}, 'novel': {'python': 2}, 'kailash': {'python': 5}}\n",
      "total avalible book: 51\n",
      "\n",
      "        type 1 to add_book\n",
      "        type 2 to stock details\n",
      "        type 3 to borrow_book\n",
      "        type 4 to return_book\n",
      "        type 5 to exit\n",
      "        \n",
      "enter your choice:5\n",
      "😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴\n",
      "library band ho chuki h\n",
      "😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴\n"
     ]
    }
   ],
   "source": [
    "print(\"welcome to library\")\n",
    "print(\"\\U0001F604\")\n",
    "while True:\n",
    "    user_name=input(\"enter your user_name:\")\n",
    "    password=input(\"enter your password(alphanumeric):\")\n",
    "    if user_name.lower()==\"mohitgupta\" and password==\"mohit@22\":\n",
    "        print(\"successfully login.\")\n",
    "    else:\n",
    "        print(\"plz enter valid username and password:\")\n",
    "        continue\n",
    "    book={\"python\":10,\"java\":20,\"math\":10,\"novel\":20}\n",
    "    total_book=0\n",
    "    for i in book.values():\n",
    "        total_book+=i\n",
    "    borrow_book={}\n",
    "    reu_book={}\n",
    "    while True:\n",
    "        print(\"total avalible book:\",total_book)\n",
    "        print(\"\"\"\n",
    "        type 1 to add_book\n",
    "        type 2 to stock details\n",
    "        type 3 to borrow_book\n",
    "        type 4 to return_book\n",
    "        type 5 to exit\n",
    "        \"\"\")\n",
    "        choice=input(\"enter your choice:\")\n",
    "        if choice==\"1\":\n",
    "            book_name=input(\"enter your book:\")\n",
    "            quantity=int(input(\"how many book you add:\"))\n",
    "            if book_name in book:\n",
    "                book[book_name]+=quantity\n",
    "                total_book+= quantity\n",
    "                continue\n",
    "            book[book_name]=quantity\n",
    "            total_book+=quantity\n",
    "            print(book)\n",
    "            print(\"book added successfully\")\n",
    "        elif choice==\"2\":\n",
    "            print(\"stock details\")\n",
    "            print(\"\"\"\n",
    "            press 1 for available book details\n",
    "            prees 2 for borrow book details\n",
    "            press 3 for return book details\n",
    "            \"\"\")\n",
    "            ac=input(\"enter above option:\")\n",
    "            if ac==\"1\":\n",
    "                print(\"avalible book\")\n",
    "                print(\"book name\",\"\\t\",\"quantity\")\n",
    "                for w,v in book.item,():\n",
    "                    print(w,\"\\t\\t\",v)\n",
    "            elif ac==\"2\":\n",
    "                print(\"borrow book detalis\")\n",
    "                print(borrow_book)\n",
    "            elif ac==\"3\":\n",
    "                print(\"return book detalis\")\n",
    "                print(reu_book)\n",
    "            else:\n",
    "                print(\"plz enter valid input:\")\n",
    "        elif choice==\"3\":\n",
    "            if total_book==0:\n",
    "                print(\"you can't borrow library is empty:\")\n",
    "                continue\n",
    "            print(\"avalible book\")\n",
    "            print(\"book name\",\"\\t\",\"quantity\")\n",
    "            for w,v in book.items():\n",
    "                print(w,\"\\t\\t\",v)\n",
    "            student_name=input(\"enter your name:\")\n",
    "            if student_name in borrow_book:\n",
    "                print(\"{student_name}you already borrow book\")\n",
    "                continue\n",
    "            b_borrow=input(\"which book you want:\").strip()\n",
    "            b_quantity=int(input(\"how many book you want:\"))\n",
    "            if book[b_borrow]==0:\n",
    "                print(\"{b_borrow}book is out of stock\")\n",
    "                continue\n",
    "            if b_quantity>book[b_borrow]:\n",
    "                print(\"sorry that much quantity you want not available\")\n",
    "                continue\n",
    "            book[b_borrow]-=b_quantity\n",
    "            total_book-=b_quantity\n",
    "            borrow_book[student_name]={b_borrow:b_quantity}\n",
    "            print(\"successfully borrowed\")\n",
    "        elif choice==\"4\":\n",
    "            if borrow_book=={}:\n",
    "                print(\"first borrow book then return\")\n",
    "                continue\n",
    "            student_name=input(\"enter your name:\")\n",
    "            b_return=input(\"enter your return book name:\").strip()\n",
    "            if student_name in borrow_book:\n",
    "                pass\n",
    "            else:\n",
    "                print(\"enter valid name:\")\n",
    "                continue\n",
    "            if b_return not in borrow_book[student_name]:\n",
    "                print(\"plz enter valid book name:\")\n",
    "                continue\n",
    "            r_quantity=int(input(\"enter return book quantity:\"))\n",
    "            if r_quantity>borrow_book[student_name][b_return]:\n",
    "                print(\"return quantity is more than your borrow quantity:\")\n",
    "                continue\n",
    "            elif r_quantity<borrow_book[student_name][b_return]:\n",
    "                print(\"return quantity is less than your borrow quantity:\")\n",
    "                continue\n",
    "            reu_book[student_name]={b_return:r_quantity}#add detail of return student\n",
    "            book[b_return]+=r_quantity\n",
    "            print(\"successfully return:\")\n",
    "            if borrow_book[student_name][b_return]==reu_book[student_name][b_return]:\n",
    "                del borrow_book[student_name]\n",
    "            total_book+=r_quantity\n",
    "        \n",
    "        elif choice==\"5\":\n",
    "            print(\"\\U0001F634\"*30)\n",
    "            print(\"library band ho chuki h\")\n",
    "            print(\"\\U0001F634\"*30)\n",
    "            \n",
    "            break\n",
    "        else:\n",
    "            print(\"plz enter valid options\")\n",
    "            continue\n",
    "    if choice==\"5\":\n",
    "        break\n",
    "        \n",
    "            \n",
    "            "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "069bf4c9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
